### ISSUE TITLE
Es ist ein Fehler beim Suchen nach Volltextsuche aufgetreten if Circles App is enabled

### ISSUE THREAD

**Issue by apg1980** [nextcloud/circles#763] opened 2021-08-03 05:21 UTC
Hello i am using Nextcloud 22 on PHP8 with Apache.
The Fulltextsearch is throwing "Es ist ein Fehler beim Suchen nach Volltextsuche aufgetreten" while searching if the Circles App is enabled.

**Comment by small1** [comment] 2021-08-05 18:21
This is reported in the circles app here: https://github.com/nextcloud/fulltextsearch/issues/643
Dont know if its a circles o fulltextsearch problem. But it does exist on both upgraded and new installs.

I just did a fresh install for a client and the bug is there.

**Comment by small1** [comment] 2021-08-05 18:33
I did some additional testing. The error is generated through a call in fulltextsearch  so the question is if circles are missing a this method: $rights->setCircles(Circles::joinedCircleIds($user->getUID()));  

Or if it was removed but not fixed in fulltextsearch

**Comment by small1** [comment] 2021-08-12 08:23
This can be closed as it has been fixed and is a duplicate of #777

**Closed** 2021-12-30 12:48 UTC
