### ISSUE TITLE
inviting members

### ISSUE THREAD

**Issue by MiGo2000** [nextcloud/circles#178] opened 2018-03-05 09:13 UTC
After Update to nextcloud 13 I cannot invite members to a circle. There is a message on the right side, but it is too fast gone to read it

**Comment by fgsl** [comment] 2018-03-05 14:16
@MiGo2000, is there something in log file about it?

**Comment by MiGo2000** [comment] 2018-03-05 20:52
No log entries.
Deactivated the app, removed it, reactivated it --> it works as it should.
Thank you, Michael

**Comment by armeris** [comment] 2018-04-28 10:09
I have the same problem. I've tried to deactivate and remove the app and then reinstall but the problem remains. There's no error in the logs nor the JS console.
It is happening with Firefox desktop version, with the mobile version it seems to work.

**Comment by lvarnava** [comment] 2018-09-19 13:26
I think this is the same problem
https://github.com/nextcloud/circles/issues/227

**Comment by joshtrichards** [comment] 2024-06-13 20:36
Cannot reproduce this problem today. Closing.

**Closed by joshtrichards** 2024-06-13 20:36 UTC
