### ISSUE TITLE
Class OCA\\Circles\\ShareByCircleProvider contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (OCP\\Share\\IShareProvider::restore) at /apps/circles/lib/ShareByCircleProvider.php#64

### ISSUE THREAD

**Issue by djpremier** [nextcloud/circles#216] opened 2018-07-28 01:40 UTC
Nextcloud 14

```
{
    "reqId":"Pq1pqYkVASRVAykEvqXU",
    "level":3,
    "time":"2018-07-28T00:53:28+00:00",
    "remoteAddr":"HIDDEN",
    "user":"admin",
    "app":"PHP",
    "method":"POST",
    "url":"\/index.php\/login",
    "message":"Class OCA\\Circles\\ShareByCircleProvider contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (OCP\\Share\\IShareProvider::restore) at \/var\/www\/nextcloud_14\/apps\/circles\/lib\/ShareByCircleProvider.php#64",
    "userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/67.0.3396.99 Safari\/537.36",
    "version":"14.0.0.13"
}
```

**Comment by juliushaertl** [comment] 2018-07-31 13:55
Duplicate of https://github.com/nextcloud/circles/issues/215

**Closed by juliushaertl** 2018-07-31 13:55 UTC
