### ISSUE TITLE
users cannot accept or refuse an invitation (notification stays)

### ISSUE THREAD

**Issue by JayBeRayBearGun** [nextcloud/circles#595] opened 2021-05-08 13:02 UTC
On a fresh install NC21 (docker version) I created a closed circle and invited to users. They see the notification but up clicking on accept it shoud "failed to perform action". Refuse also does not work. However when switching to the circles app accepting does work! (did not test refuse yet). So it seems to be a matter of integration/handling of the notifications.

Requests are handled correctly through the notifications dialogue.

**Comment by joshtrichards** [comment] 2024-06-13 20:38
Duplicate of #810

**Closed by joshtrichards** 2024-06-13 20:38 UTC
