### ISSUE TITLE
nc Teams, Members are displayed incompletely

### ISSUE THREAD

**Issue by hhochhard** [nextcloud/circles#1681] opened 2024-09-05 08:54 UTC
I have created a team with 42 members, but only 29 of them are displayed

**Comment by hhochhard** [comment] 2024-09-11 18:13
[index] Fehler: Could not find organizer
	GET /index.php/apps/calendar/v1/circles/getmembers?format=json&circleId=dM4OjL6fdOfOWwuu7r3qM2lCLEoxwJm
	von 94.134.111.54 von hhochhard um 11.09.2024, 19:59:23
{"reqId":"ZuHaew4j20uWvxo3D3w8QQAAAJY","level":3,"time":"2024-09-11T17:59:23+00:00","remoteAddr":"94.134.111.54","user":"hhochhard","app":"index","method":"GET","url":"/index.php/apps/calendar/v1/circles/getmembers?format=json&circleId=dM4OjL6fdOfOWwuu7r3qM2lCLEoxwJm","message":"Could not find organizer","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:130.0) Gecko/20100101 Firefox/130.0 Config/91.2.2258.14","version":"29.0.5.1","exception":{"Exception":"OCA\\Calendar\\Service\\ServiceException","Message":"Could not find organizer","Code":0,"Trace":[{"file":"/www/htdocs/w01f045a/cloud.hamburger-singakademie.de/lib/private/AppFramework/Http/Dispatcher.php","line":232,"function":"getCircleMembers","class":"OCA\\Calendar\\Controller\\ContactController","type":"->","args":["dM4OjL6fdOfOWwuu7r3qM2lCLEoxwJm"]},{"file":"/www/htdocs/w01f045a/cloud.hamburger-singakademie.de/lib/private/AppFramework/Http/Dispatcher.php","line":138,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\Calendar\\Controller\\ContactController"],"getCircleMembers"]},{"file":"/www/htdocs/w01f045a/cloud.hamburger-singakademie.de/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\Calendar\\Controller\\ContactController"],"getCircleMembers"]},{"file":"/www/htdocs/w01f045a/cloud.hamburger-singakademie.de/lib/private/Route/Router.php","line":338,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Calendar\\Controller\\ContactController","getCircleMembers",["OC\\AppFramework\\DependencyInjection\\DIContainer"],["calendar.contact.getcirclemembers"]]},{"file":"/www/htdocs/w01f045a/cloud.hamburger-singakademie.de/lib/base.php","line":1053,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/calendar/v1/circles/getmembers"]},{"file":"/www/htdocs/w01f045a/cloud.hamburger-singakademie.de/index.php","line":49,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/www/htdocs/w01f045a/cloud.hamburger-singakademie.de/apps/calendar/lib/Controller/ContactController.php","Line":233,"message":"Could not find organizer","exception":[],"CustomMessage":"Could not find organizer"},"id":"66e1db0c89ca8"}

**Comment by joshtrichards** [comment] 2024-10-02 20:59
Duplicate of #1644

**Closed by joshtrichards** 2024-10-02 20:59 UTC
