### ISSUE TITLE
Group members not updated

### ISSUE THREAD

**Issue by susnux** [nextcloud/circles#1166] opened 2022-09-26 16:32 UTC
We use circles with the collectives app, now I noticed after updating to 24.0.5 that some users can not see their collectives or shared files if they are members of a group which is the member of the circle.

E.g. our setup is similar to:
* LDAP groups:
  * `member`
  * `events`
* Collectives (= circles)
  * `event team` -> owner: user admin, members: group `events`
  * `help` -> owner: user admin, members: group `member`

An user who is member of `member` and `events` can only see shares of circles `event team` but not of `help`.
(This is a bit more complex as there are more circle <-> group mappings, and some work but some do not.)

I am not sure what information I can provide to track this down, it first appeared when updating to 24.0.5 from 24.0.3.

**Comment by susnux** [comment] 2022-09-27 19:32
The only difference between circles that work and the ones that do not work is that the API response says:
`initiator: null`

for the not working ones.

**Comment by mejo-** [comment] 2023-10-24 14:31
Closing as duplicate of #1249 (because that issue has more discussion).

**Closed by mejo-** 2023-10-24 14:31 UTC
