### ISSUE TITLE
Unhandled Exception when trying to enable circles

### ISSUE THREAD

**Issue by Af0x** [nextcloud/circles#1595] opened 2024-06-01 11:59 UTC
Hello,

I get the following error when trying to enable circles. Had to disable it because there was an Internal Server Error preventing the webinterface to load:

```
occ app:enable circles
An unhandled exception has been thrown:
Error: Class "OCA\Circles\Model\Circle" not found in /path/to/nextcloud/apps/circles/lib/Service/FederatedUserService.php:573
Stack trace:
#0 /path/to/nextcloud/apps/circles/lib/Service/MigrationService.php(195): OCA\Circles\Service\FederatedUserService->getAppInitiator()
#1 /path/to/nextcloud/apps/circles/lib/Migration/Migration.php(97): OCA\Circles\Service\MigrationService->migration()
#2 /path/to/nextcloud/lib/private/Repair.php(124): OCA\Circles\Migration\Migration->run()
#3 /path/to/nextcloud/lib/private/legacy/OC_App.php(838): OC\Repair->run()
#4 /path/to/nextcloud/lib/private/Installer.php(141): OC_App::executeRepairSteps()
#5 /path/to/nextcloud/core/Command/App/Enable.php(110): OC\Installer->installApp()
#6 /path/to/nextcloud/core/Command/App/Enable.php(80): OC\Core\Command\App\Enable->enableApp()
#7 /path/to/nextcloud/3rdparty/symfony/console/Command/Command.php(298): OC\Core\Command\App\Enable->execute()
#8 /path/to/nextcloud/3rdparty/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#9 /path/to/nextcloud/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#10 /path/to/nextcloud/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#11 /path/to/nextcloud/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run()
#12 /path/to/nextcloud/console.php(102): OC\Console\Application->run()
#13 /path/to/nextcloud/occ(11): require_once('...')
```

The issue first occurred after upgrading from nextcloud-28.0.5.1 to nextcloud-28.0.6.1 and persists after upgrading to Nextcloud 29.0.1.

**Comment by rjlan** [comment] 2024-06-01 12:42
I just got this one after upgrading from 29.0.0.19 -> 29.0.1.1
Got an internal server error message on the webui. Disabling circles fixed the issue. Same message if I try to enable it

**Comment by ndurchx** [comment] 2024-06-01 12:58
Just occured to me after updating two other plugins

**Comment by Vdauphin** [comment] 2024-06-01 14:34
Same when updating from nextcloud-28.0.5.1 to nextcloud-28.0.6.1 

```
    Erreur interne du serveur

    Le serveur est incapable d’exécuter votre requête.
    Si cela se reproduit, veuillez envoyer les détails techniques ci-dessous à l’administrateur du serveur.
    Le fichier journal du serveur peut fournir plus de renseignements.
    Renseignements techniques

        Adresse distante : XXXX
        ID de la demande : XXXX
```
[nextcloud_short.log](https://github.com/user-attachments/files/15522181/nextcloud_short.log)


Resolved by: `docker exec -u www-data $(docker ps --filter name='srv-captain--nextcloud.1' -q) php occ app:disable circles`
And repair: `docker exec -u www-data $(docker ps --filter name='srv-captain--nextcloud.1' -q) php occ maintenance:repair`
Followed by a container restart

**Comment by muelli75** [comment] 2024-06-01 15:23
I have the same problem after updating from 28.0.6 to 29.0.1, but natively without docker-containter.

It helped to deactivate Circles via the terminal, then you can at least log in again. 

Teams cannot be activated, because apparently a -dev version is available. Activation is prevented by the message ‘This app cannot be activated because it will make the server unstable’.

**Comment by osm-frasch** [comment] 2024-06-03 17:21
Is there any progress regarding the bugfix?

**Comment by joshtrichards** [comment] 2024-06-15 22:31
So far I've been unable to reproduce any of these behaviors.

Please share the output of:

- `occ config:list system`
- `occ app:list`

**Comment by joshtrichards** [comment] 2024-11-10 16:33
Closing due to lack of info received after >3 months.

**Closed by joshtrichards** 2024-11-10 16:33 UTC
Labels: bug
