### ISSUE TITLE
Error in nextcloud talk from circles

### ISSUE THREAD

**Issue by GVLLIFESTYLE** [nextcloud/circles#1280] opened 2023-03-21 11:17 UTC
`{"reqId":"z8b1zj9uoj3K55qpVy1n","level":3,"time":"2023-03-21T11:06:51+00:00","remoteAddr":"IP","user":"user1","app":"no app in context","method":"GET","url":"/nextcloud/ocs/v2.php/apps/related_resources/related/talk?itemId=583rjcum&format=json","message":"OCA\\Circles\\CirclesManager::getCurrentFederatedUser(): Return value must be of type OCA\\Circles\\IFederatedUser, null returned in file '/var/www/nextcloud/apps/circles/lib/CirclesManager.php' line 253","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36","version":"25.0.4.1","exception":{"Exception":"Exception","Message":"OCA\\Circles\\CirclesManager::getCurrentFederatedUser(): Return value must be of type OCA\\Circles\\IFederatedUser, null returned in file '/var/www/nextcloud/apps/circles/lib/CirclesManager.php' line 253","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/ocs/v1.php","line":63,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/ocs/v2.php","line":23,"args":["/var/www/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":165,"Previous":{"Exception":"TypeError","Message":"OCA\\Circles\\CirclesManager::getCurrentFederatedUser(): Return value must be of type OCA\\Circles\\IFederatedUser, null returned","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/related_resources/lib/RelatedResourceProviders/FilesRelatedResourceProvider.php","line":207,"function":"getCurrentFederatedUser","class":"OCA\\Circles\\CirclesManager","type":"->"},{"file":"/var/www/nextcloud/apps/related_resources/lib/RelatedResourceProviders/FilesRelatedResourceProvider.php","line":106,"function":"getItemIdsFromParentPath","class":"OCA\\RelatedResources\\RelatedResourceProviders\\FilesRelatedResourceProvider","type":"->"},{"file":"/var/www/nextcloud/apps/related_resources/lib/Service/RelatedService.php","line":226,"function":"getRelatedFromItem","class":"OCA\\RelatedResources\\RelatedResourceProviders\\FilesRelatedResourceProvider","type":"->"},{"file":"/var/www/nextcloud/apps/related_resources/lib/Service/RelatedService.php","line":189,"function":"getRelatedFromItem","class":"OCA\\RelatedResources\\Service\\RelatedService","type":"->"},{"file":"/var/www/nextcloud/apps/related_resources/lib/Service/RelatedService.php","line":118,"function":"retrieveRelatedToItem","class":"OCA\\RelatedResources\\Service\\RelatedService","type":"->"},{"file":"/var/www/nextcloud/apps/related_resources/lib/Controller/ApiController.php","line":103,"function":"getRelatedToItem","class":"OCA\\RelatedResources\\Service\\RelatedService","type":"->"},{"file":"/var/www/nextcloud/apps/related_resources/lib/Controller/ApiController.php","line":131,"function":"getRelatedResources","class":"OCA\\RelatedResources\\Controller\\ApiController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":225,"function":"getRelatedAlternate","class":"OCA\\RelatedResources\\Controller\\ApiController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":133,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/ocs/v1.php","line":63,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/ocs/v2.php","line":23,"args":["/var/www/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/nextcloud/apps/circles/lib/CirclesManager.php","Line":253},"CustomMessage":"--"},"id":"64198fd656481"}`

Version Talk: 15.0.4
NC Server:25.0.4
Circles: 25.0.0

**Comment by joshtrichards** [comment] 2024-06-13 18:29
Hi @GVLLIFESTYLE - Are you still experiencing this?

**Comment by joshtrichards** [comment] 2024-06-13 18:35
Duplicate of #1278

**Comment by GVLLIFESTYLE** [comment] 2024-06-13 18:35
No, ypu can close it
-------- Ursprüngliche Nachricht --------Von: Josh ***@***.***> Datum: 13.06.24  20:30  (GMT+01:00) An: nextcloud/circles ***@***.***> Cc: GVL ***@***.***>, Mention ***@***.***> Betreff: Re: [nextcloud/circles] Error in nextcloud talk from circles (Issue
  #1280) 
Hi @GVLLIFESTYLE - Are you still experiencing this?

**Closed by joshtrichards** 2024-06-13 18:35 UTC
Labels: bug, needs info
