### ISSUE TITLE
Problem when setting expiration date

### ISSUE THREAD

**Issue by giorgiopaolucci** [nextcloud/circles#220] opened 2018-08-02 15:11 UTC
Hello everybody.
I'm using nextcloud 12.0.5 with circles 0.14.1. on a debian stretch 64bit.
When I try to share a file to a circle and set an expiration date, the calendar pops up as usual, but when I try to select a date nothing happens and an "invalid date" strings appears on the expiration date field.
Expiration date works with no problems using normal users or groups.....

Any clues?

Thanks in advance.

**Comment by fgsl** [comment] 2018-09-05 12:02
Hi, @giorgiopaolucci. I couldn't reproduce this bug.
Can you send log of backend and browser generated along this action?

**Comment by joshtrichards** [comment] 2024-06-15 15:16
Closing due to a lack of follow-up info provided >5 years ago. :)
Also, #286

**Closed by joshtrichards** 2024-06-15 15:16 UTC
