### ISSUE TITLE
The option to federate the circles does not appear

### ISSUE THREAD

**Issue by susobaco** [nextcloud/circles#539] opened 2020-12-23 12:00 UTC
Hi, I'm using nexcloud 20.0.0.4 on debian buster. I have installed the circles app, but I can't find anywhere in the admin configuration panel the option to federate the circles, as mentioned in this post:
https://help.nextcloud.com/t/circles-0-11-0-user-management-federated-circles-activities/14101
I may be very clumsy and you don't see it, can someone tell me where it is?

occ $ circles:test
- GET request on https:/********************/csrftoken: 200
- POST request on https://******************/apps/circles/v1/gs/broadcast/async/test-dummy-token/: 200
- Async request is sent, now waiting 5 seconds
- Pause is over, checking results for f6c8a22a-b007-4671-9476-c347e42eed1c
******************* ok

Thanks.

**Comment by daita** [comment] 2020-12-28 15:46
#511 duplicate of

**Closed by daita** 2020-12-28 15:46 UTC
