### ISSUE TITLE
Missing primary keys for DB clusters

### ISSUE THREAD

**Issue by rullzer** [nextcloud/circles#559] opened 2021-02-18 08:14 UTC
The table `oc_circle_gsevents` is missing a primary key.
Some DB setups **require** each table to have a primary key

**Comment by acsfer** [comment] 2021-04-20 09:30
Duplicate of https://github.com/nextcloud/circles/issues/534

**Comment by acsfer** [comment] 2022-01-09 21:16
`oc_circles_event` is also missing a PK

**Comment by ArtificialOwl** [comment] 2022-01-10 12:29
this is fixed in next release

**Closed by ArtificialOwl** 2022-01-10 12:29 UTC

**Comment by solracsf** [comment] 2022-04-25 21:25
Hi @ArtificialOwl in my setup (v22.2.7) these are missing a PK:

```
oc_circles_event
oc_circle_gsevents
```

what release do you mean?
