### ISSUE TITLE
Circles break 23.0.2

### ISSUE THREAD

**Issue by digital-codes** [nextcloud/circles#930] opened 2022-02-21 15:19 UTC
Update fails: nextcloud log:

```
{"reqId":"YhOqhnMJ2L7zRVRF26GlfQAAAAI","level":3,"time":"2022-02-21T15:06:46+00:00",,"app":"index","method":"GET","url":"/","message":"Argument 1 passed to OCA\\Circles\\Service\\FederatedUserService::deserializeJson() must be of the type string, bool given, called in /var/www/html/nextcloud/apps/circles/lib/Service/FederatedUserService.php on line 1211","userAgent":"Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:97.0) Gecko/20100101 Firefox/97.0","version":"23.0.2.1","exception":{"Exception":"TypeError","Message":"Argument 1 passed to OCA\\Circles\\Service\\FederatedUserService::deserializeJson() must be of the type string, bool given, called in /var/www/html/nextcloud/apps/circles/lib/Service/FederatedUserService.php on line 1211","Code":0,"Trace":[{"file":"/var/www/html/nextcloud/apps/circles/lib/Service/FederatedUserService.php","line":1211,"function":"deserializeJson","class":"OCA\\Circles\\Service\\FederatedUserService","type":"->","args":[false,"OCA\\Circles\\Model\\Circle"]},{"file":"/var/www/html/nextcloud/apps/circles/lib/Service/FederatedUserService.php","line":939,"function":"getCachedSingleCircle","class":"OCA\\Circles\\Service\\FederatedUserService","type":"->","args":[{"__class__":"OCA\\Circles\\Model\\FederatedUser"}]},{"file":"/var/www/html/nextcloud/apps/circles/lib/Service/FederatedUserService.php","line":911,"function":"getSingleCircle","class":"OCA\\Circles\\Service\\FederatedUserService","type":"->","args":[{"__class__":"OCA\\Circles\\Model\\FederatedUser"},true]},{"file":"/var/www/html/nextcloud/apps/circles/lib/Service/FederatedUserService.php","line":489,"function":"fillSingleCircleId","class":"OCA\\Circles\\Service\\FederatedUserService","type":"->","args":[{"__class__":"OCA\\Circles\\Model\\FederatedUser"},true]},{"file":"/var/www/html/nextcloud/apps/circles/lib/ShareByCircleProvider.php","line":553,"function":"getLocalFederatedUser","class":"OCA\\Circles\\Service\\FederatedUserService",

... etc ...

```

Disabling circles helps ...

**Comment by chriscroome** [comment] 2022-02-28 12:27
I have come across this issue also, with one Nextcloud site with one user who couldn't login (HTTP 500 errors) after the upgrade to Nextcloud 23.0.2, after disabling the Circles app she could login again, in the Nextcloud log this appears to be the error:

> Argument 1 passed to OCA\\Circles\\Service\\FederatedUserService::deserializeJson() must be of the type string, bool given, called in /apps/circles/lib/Service/FederatedUserService.php on line 1211"

**Comment by chriscroome** [comment] 2022-02-28 12:56
This looks like a dupe of this bug?

https://github.com/nextcloud/circles/issues/928

**Comment by ArtificialOwl** [comment] 2022-03-04 09:51
please test this: https://github.com/nextcloud/circles/pull/929

**Closed** 2022-04-19 12:51 UTC
Labels: needs info
