### ISSUE TITLE
Eroor Messages from Cron

### ISSUE THREAD

**Issue by khoschi** [nextcloud/circles#573] opened 2021-04-01 10:25 UTC
This is still - or again - an issue, speaking of #513 and #483 and Circles 0.20.7 - any chance to get rid of it?
Messages stack up with cron.

Log (with always changing IDs): 

{"reqId":"S2kyuXNUQqhbD2wyYLGW","level":3,"time":"2021-03-23T12:10:17+00:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":{"Exception":"TypeError","Message":"Argument 2 passed to OCA\\Circles\\Db\\CirclesRequest::getCircle() must be of the type string, null given, called in /var/www/html/apps/circles/lib/Service/CirclesService.php on line 277","Code":0,"Trace":[{"file":"/var/www/html/apps/circles/lib/Service/CirclesService.php","line":277,"function":"getCircle","class":"OCA\\Circles\\Db\\CirclesRequest","type":"->"},{"file":"/var/www/html/apps/circles/lib/Api/v1/Circles.php","line":265,"function":"detailsCircle","class":"OCA\\Circles\\Service\\CirclesService","type":"->"},{"file":"/var/www/html/apps/deck/lib/Service/PermissionService.php","line":265,"function":"detailsCircle","class":"OCA\\Circles\\Api\\v1\\Circles","type":"::"},{"file":"/var/www/html/apps/deck/lib/Notification/NotificationHelper.php","line":98,"function":"findUsers","class":"OCA\\Deck\\Service\\PermissionService","type":"->"},{"file":"/var/www/html/apps/deck/lib/Cron/ScheduledNotifications.php","line":62,"function":"sendCardDuedate","class":"OCA\\Deck\\Notification\\NotificationHelper","type":"->"},{"file":"/var/www/html/lib/private/BackgroundJob/Job.php","line":52,"function":"run","class":"OCA\\Deck\\Cron\\ScheduledNotifications","type":"->"},{"file":"/var/www/html/cron.php","line":127,"function":"execute","class":"OC\\BackgroundJob\\Job","type":"->"}],"File":"/var/www/html/apps/circles/lib/Db/CirclesRequest.php","Line":192,"CustomMessage":"Error while running background job (class: OCA\\Deck\\Cron\\ScheduledNotifications, arguments: )"},"userAgent":"--","version":"20.0.8.1"}

**Comment by acsfer** [comment] 2021-04-19 19:03
Duplicate of https://github.com/nextcloud/circles/issues/563

**Closed by acsfer** 2021-04-19 19:03 UTC
