### ISSUE TITLE
Updating failed on NC 16.04

### ISSUE THREAD

**Issue by vadiof** [nextcloud/circles#345] opened 2019-10-21 11:22 UTC
Trying updating Circles on NC 16.04 I get this message:

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE TABLE `oc_circles_tokens` (`circle_id` VARCHAR(31) NOT NULL, `user_id` VARCHAR(255) NOT NULL, `share_id` BIGINT NOT NULL, `token` VARCHAR(31) NOT NULL, `password` VARCHAR(127) NOT NULL, PRIMARY KEY(`circle_id`, `user_id`, `share_id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ENGINE = InnoDB ROW_FORMAT = compressed': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

DB version is
mysql  Ver 15.1 Distrib 10.1.41-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**Comment by joshtrichards** [comment] 2024-06-15 12:32
Duplicate of #383

**Closed by joshtrichards** 2024-06-15 12:32 UTC
