### ISSUE TITLE
Can't login after update to 25 with cicles enabled

### ISSUE THREAD

**Issue by dantriano** [nextcloud/circles#1197] opened 2022-10-29 18:35 UTC
After update to the new Nextcloud 25 version I get the error 500 when I try to login. I need to disable circles ./occ app:disable circles to get nextcloud working again.

Error Message:
PHP message: PHP Fatal error: Nesting level too deep - recursive dependency? in /var/www/html/lib/private/Log/ExceptionSerializer.php on line 215

**Comment by MenschenToaster** [comment] 2022-10-30 23:43
Can confirm

**Comment by MenschenToaster** [comment] 2022-10-30 23:44
Its seems to be a fix to remove and re-add the email to the users thoguh. But to be safe I disabled the app completly

**Comment by Volker-K** [comment] 2022-11-04 06:01
Same with migrating to 24.0.3, described here: https://github.com/nextcloud/server/issues/32432
We need Circles so we're stuck un NC 23 right now.

**Comment by Volker-K** [comment] 2022-11-23 09:46
@szaimen You've linkt his issue in https://github.com/nextcloud/all-in-one/issues/1280 where I don't find it anymore. Is it solved?

**Comment by szaimen** [comment] 2022-11-23 11:44
No, it is not solved yet, IIRC. @ArtificialOwl can have a look hopefully soon.

**Comment by ultrasites** [comment] 2022-11-24 20:32
The bug is still relevant. My instance: Upgrade 24.0.x to 25.0.1 via docker. When it will be fixed? My user cannot login into nextcloud.

**Comment by ArtificialOwl** [comment] 2022-11-28 10:45
You should be able to bypass the issue by running this command:

>     ./occ config:app:set circles route_to_circles --value ''

**Comment by Volker-K** [comment] 2022-11-29 08:24
> You should be able to bypass the issue by running this command:
> 
> > ```
> > ./occ config:app:set circles route_to_circles --value ''
> > ```
> 
> #1189

As you can see in https://github.com/nextcloud/server/issues/32432 this does not solve the problem in all cases. It's not clear, why only few installations are having this problem at all. In our stageing all works fine, live got this error after migrating NC, but I couldn't reproduce it in a copy of live environment. 
A new migration of live env will be a blind flight.

**Comment by ArtificialOwl** [comment] 2022-11-29 10:42
wow, by bad ...

the setting is 

>     ./occ config:app:set circles route_to_circle --value ''

Can you check if this works ?

**Comment by Volker-K** [comment] 2022-11-29 11:24
> wow, by bad ...
> 
> the setting is
> 
> > ```
> > ./occ config:app:set circles route_to_circle --value ''
> > ```
> 
> Can you check if this works ?

I'd have to migrate our live environment with 5k users for this and run into the error becaus I didn't get it reproduced.

I could possibly try between christmas and new year's eve.

**Comment by nilshellerhoff** [comment] 2022-11-29 12:01
> wow, by bad ...
> 
> the setting is
> 
> > ```
> > ./occ config:app:set circles route_to_circle --value ''
> > ```
> 
> Can you check if this works ?

Unfortunately this does not work in my case (Nextcloud 24.0.7). As I don't need the circles app, it's not that important for me, but just letting you know.

**Comment by Volker-K** [comment] 2022-11-30 10:55
Possibly it's a problem with a deactivated (or outdated?) contacts-app?
https://github.com/nextcloud/server/issues/32432#issuecomment-1331723583

**Comment by ultrasites** [comment] 2022-11-30 12:38
> wow, by bad ...
> 
> the setting is
> 
> > ```
> > ./occ config:app:set circles route_to_circle --value ''
> > ```
> 
> Can you check if this works ?

it fix the bug for a moment.....the bug is back now...

**Comment by ultrasites** [comment] 2022-11-30 13:58
> > > wow, by bad ...
> > > the setting is
> > > > ```
> > > > ./occ config:app:set circles route_to_circle --value ''
> > > > ```
> > > 
> > > 
> > > Can you check if this works ?
> > 
> > 
> > it fix the bug for a moment.....the bug is back now...
> 
> Do you have both Circles _and_ Contacts App enabled?

Circles -> enabled
Contacts -> disabled

**Comment by Volker-K** [comment] 2022-12-01 06:12
> > > > wow, by bad ...
> > > > the setting is
> > > > > ```
> > > > > ./occ config:app:set circles route_to_circle --value ''
> > > > > ```
> > > > 
> > > > 
> > > > Can you check if this works ?
> > > 
> > > 
> > > it fix the bug for a moment.....the bug is back now...
> > 
> > 
> > Do you have both Circles _and_ Contacts App enabled?
> 
> Circles -> enabled Contacts -> disabled

Could you enable Contacts? Circles are quite useless without Contacts App since the UI to manage Circles has moved into Contacts. 

I now can reproduce the error by disabling Contacts in our stageing system, but I don't know why it happend in our live system after migrating. Possibly that day there was a problem with App versions and Contacts was disabled.

**Comment by PVince81** [comment] 2023-01-04 13:01
@ArtificialOwl can you confirm if this was resolved ? I remember merging some PRs that might have been related

**Comment by blizzz** [comment] 2023-09-14 18:41
Is this relevant > NC 25?

**Comment by sselka** [comment] 2023-09-27 16:42
looks like it is solved :)

**Closed** 2023-09-28 08:32 UTC
Labels: bug
