### ISSUE TITLE
Adding users to circle does not work anymore

### ISSUE THREAD

**Issue by hertz879** [nextcloud/circles#469] opened 2020-08-02 20:47 UTC
When I try to add a user to a circle it looks like it worked, but after a reload the change is gone. In fact the user is never added to the circle (when trying to change the users role directly after adding them, an error shows, saying the user is not a member of this circle). Additionally I cannot approve users which requested access to a closed circle, instead the same thing happens. I see nothing in the server logs related to this. The Firefox console says: 

```
$ is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 4 globals.js:61:15
The escapeHTML library is deprecated! It will be removed in nextcloud 19.  2 globals.js:61:15
```
but I guess that comes from searching the users.

I do see this message in the logs sometimes, but not at the same time I try adding a user:
```
{"reqId":"2mePBB5oDrKso5CJJtqF","level":3,"time":"2020-08-02T19:15:11+02:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":{"Exception":"TypeError","Message":"Argument 2 passed to OCA\\Circles\\Db\\CirclesRequest::getCircle() must be of the type string, null given, called in /var/www/nextcloud/apps/circles/lib/Service/CirclesService.php on line 259","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/circles/lib/Service/CirclesService.php","line":259,"function":"getCircle","class":"OCA\\Circles\\Db\\CirclesRequest","type":"->"},{"file":"/var/www/nextcloud/apps/circles/lib/Api/v1/Circles.php","line":251,"function":"detailsCircle","class":"OCA\\Circles\\Service\\CirclesService","type":"->"},{"file":"/var/www/nextcloud/apps/deck/lib/Service/PermissionService.php","line":266,"function":"detailsCircle","class":"OCA\\Circles\\Api\\v1\\Circles","type":"::"}
```
But maybe it gives you a hint what could be wrong?

Joining public circles actively still works as expected.

**Comment by SLYtiger16** [comment] 2020-08-03 16:58
Duplicate of #465

**Closed by SLYtiger16** 2020-08-03 16:58 UTC

**Comment by hertz879** [comment] 2020-08-08 15:22
Oh sorry, totally true. I somehow must have overlooked it.
