### ISSUE TITLE
Circle not work on fresh installed Nextcloud 22

### ISSUE THREAD

**Issue by Mannshoch** [nextcloud/circles#731] opened 2021-07-23 13:04 UTC
After Installation the Circle app is no accessible.
```
[{"reqId":"YPXv0FFZuDArWVzRcDpehwAAAAg","level":3,"time":"2021-07-19T21:34:09+00:00","remoteAddr":"213.196.188.22","user":"--","app":"PHP","method":"GET","url":"/cron.php","message":"Cannot modify header information - headers already sent by (output started at /nextcloud/apps/circles/lib/Service/MaintenanceService.php:143) at /nextcloud/lib/private/legacy/OC_JSON.php#113","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0","version":"22.0.0.11","exception":{"Exception":"Error","Message":"Cannot modify header information - headers already sent by (output started at /nextcloud/apps/circles/lib/Service/MaintenanceService.php:143) at /nextcloud/lib/private/legacy/OC_JSON.php#113","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[2,"Cannot modify header information - headers already sent by (output started at /nextcloud/apps/circles/lib/Service/MaintenanceService.php:143)","/nextcloud/lib/private/legacy/OC_JSON.php",113]},{"file":"/nextcloud/lib/private/legacy/OC_JSON.php","line":113,"function":"header","args":["Content-Type: application/json; charset=utf-8"]},{"file":"/nextcloud/cron.php","line":152,"function":"success","class":"OC_JSON","type":"::","args":[]}],"File":"/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"id":"60fabc86ebec4"}
```

**Comment by czenk** [comment] 2021-07-23 14:06
+1

Symptoms:
- No icon for 'Circles' 
- Error message in log as reported by Mannshoch
- Icon to access 'Circles' UI missing from users top level app task bar, no access to a dedicated end-user ui for management of Circles (compared to NC 21 installed in same environment - see below)
- After creation of a Circle from 'Contacts App' and sharing a file with the Circle, Circle participants cannot gain visibility of the items shared with/contained in the Circle

May be related:
- Installation error at end of automated setup (via nextcloud-setup.php) when trying to install recommended apps.
- Had to install 'Groupware Bundle' + Circles manually from app section


Config Details:
Shared webhost (Apache, provider all-inkl.com)
- NC 22.0.0.11
- PHP 7.4
- Default encryption module enabled, using per-user keys

Local installation options, shared hosting and AWS resources available for reproduction/fault localisation/Fehlereingrenzung - do not hesitate to reach out in case I can be of further assistance.

Cheers

**Comment by Mannshoch** [comment] 2021-07-23 15:18
In my case:

PHP: 8
Nextcloud: 22.0.0
Default encryption module enabled
Actual only one User is setup in nextcloud

Server shared host, PHP only
Server data (by System Tab)
Linux 3.10.0-1160.25.1.el7.x86_64 x86_64
Processor: | AMD EPYC 7402P 24-Core Processor (48 cores)

**Comment by shu0406** [comment] 2021-07-26 11:31
Same here with
NC 22.0.0, PHP 7.4.3

> After creation of a Circle from 'Contacts App' and sharing a file with the Circle, Circle participants cannot gain visibility of the items shared with/contained in the Circle
> Deleting a Circle from the 'Contacts App': Circle removed from user view, but after leaving/reentering the Contacts App the previously deleted Circle is visible again. Same for attempts to remove members from Circle

**Comment by ArtificialOwl** [comment] 2021-07-29 11:51
> After Installation the Circle app is no accessible.
> 
> ```
> [{"reqId":"YPXv0FFZuDArWVzRcDpehwAAAAg","level":3,"time":"2021-07-19T21:34:09+00:00","remoteAddr":"213.196.188.22","user":"--","app":"PHP","method":"GET","url":"/cron.php","message":"Cannot modify header information - headers already sent by (output started at /nextcloud/apps/circles/lib/Service/MaintenanceService.php:143) at /nextcloud/lib/private/legacy/OC_JSON.php#113","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0","version":"22.0.0.11","exception":{"Exception":"Error","Message":"Cannot modify header information - headers already sent by (output started at /nextcloud/apps/circles/lib/Service/MaintenanceService.php:143) at /nextcloud/lib/private/legacy/OC_JSON.php#113","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[2,"Cannot modify header information - headers already sent by (output started at /nextcloud/apps/circles/lib/Service/MaintenanceService.php:143)","/nextcloud/lib/private/legacy/OC_JSON.php",113]},{"file":"/nextcloud/lib/private/legacy/OC_JSON.php","line":113,"function":"header","args":["Content-Type: application/json; charset=utf-8"]},{"file":"/nextcloud/cron.php","line":152,"function":"success","class":"OC_JSON","type":"::","args":[]}],"File":"/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"id":"60fabc86ebec4"}
> ```

This is a minor issue that is fixed in NC22.1.0 (rc1 already available)

**Comment by ArtificialOwl** [comment] 2021-07-29 13:50
@czenk this PR should fix your issue, if you're willing to test it (best if you apply the patch over nc22.1.0-rc1)

**Comment by czenk** [comment] 2021-07-30 15:18
Hi @ArtificialOwl ,

Thank you very much. 

I tried to make the patch work.
The bad news is, I did not succeed.
The good news is, I may be guilty of not deploying the patch correctly:

- Switched from stable to beta channel
- Upgraded to 22.1.0 RC1
- Created backup of circles folders
- Transfered .zip from repo https://github.com/nextcloud/circles/tree/fix/731/include-path-in-loopback onto temp folder on webspace
- Overwrote files lib/Command/CirclesCheck.php and lib/Service/ConfigService.php from circles app with files from repo (including sanity check via diff against backup post copy)

On a separate attempt I purged the circles folder (except for the 'vendor' folder contained) and copied in the full repo. This yielded an upgrade message for circles. The upgrade failed though with an error message about an incompatible upgrade/downgrade path.

Would it be of any benefit to attempt an install against the document root (not desired for production) for comparison?

**New symptoms**

occ circles:check now yields:
```* testing current address: https://host.domain.tld/22
- GET request on https://host.domain.tld/22/index.php/csrftoken: 200
- POST request on https://host.domain.tld/22/index.php/apps/circles/async/test-dummy-token/: fail

- You do not have a valid loopback address setup right now.
```
NC log contains this line after running occ circles:check:
``
{"reqId":"f4GhzFHjElgikf6VQDEv","level":3,"time":"2021-07-30T14:42:33+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Directive 'allow_url_include' is deprecated at Unknown#0","userAgent":"--","version":"22.1.0.0","id":"61040fd9a5636"} 
`` 

When I try to manipulate a circle I had created through the Contacts App earlier, NC log yields:
`` 
{"reqId":"YQQOqOY95a9mCXNSghE8iQAAAAo","level":3,"time":"2021-07-30T14:37:28+00:00","remoteAddr":"[removed]","user":"--","app":"index","method":"POST","url":"/22/index.php/login","message":"Argument 1 passed to OC\\Core\\Controller\\LoginController::tryLogin() must be of the type string, null given, called in /www/htdocs/[removed]/[removed]/22/lib/private/AppFramework/Http/Dispatcher.php on line 217","userAgent":"--","version":"22.1.0.0","exception":{"Exception":"Exception","Message":"Argument 1 passed to OC\\Core\\Controller\\LoginController::tryLogin() must be of the type string, null given, called in /www/htdocs/[removed]/[removed]/22/lib/private/AppFramework/Http/Dispatcher.php on line 217","Code":0,"Trace":[{"file":"/www/htdocs/[removed]/[removed]/22/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Core\\Controller\\LoginController"},"tryLogin"]},{"file":"/www/htdocs/[removed]/[removed]/22/lib/private/Route/Router.php","line":301,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OC\\Core\\Controller\\LoginController","tryLogin",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"core.login.tryLogin"}]},{"file":"/www/htdocs/[removed]/[removed]/22/lib/base.php","line":1000,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/login"]},{"file":"/www/htdocs/[removed]/[removed]/22/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/www/htdocs/[removed]/[removed]/22/lib/private/AppFramework/Http/Dispatcher.php","Line":158,"Previous":{"Exception":"TypeError","Message":"Argument 1 passed to OC\\Core\\Controller\\LoginController::tryLogin() must be of the type string, null given, called in /www/htdocs/[removed]/[removed]/22/lib/private/AppFramework/Http/Dispatcher.php on line 217","Code":0,"Trace":[{"file":"/www/htdocs/[removed]/[removed]/22/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"tryLogin","class":"OC\\Core\\Controller\\LoginController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/www/htdocs/[removed]/[removed]/22/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Core\\Controller\\LoginController"},"tryLogin"]},{"file":"/www/htdocs/[removed]/[removed]/22/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Core\\Controller\\LoginController"},"tryLogin"]},{"file":"/www/htdocs/[removed]/[removed]/22/lib/private/Route/Router.php","line":301,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OC\\Core\\Controller\\LoginController","tryLogin",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"core.login.tryLogin"}]},{"file":"/www/htdocs/[removed]/[removed]/22/lib/base.php","line":1000,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/login"]},{"file":"/www/htdocs/[removed]/[removed]/22/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/www/htdocs/[removed]/[removed]/22/core/Controller/LoginController.php","Line":294},"CustomMessage":"--"},"id":"61040ea9c71c7"}
``

Further symptoms from my initial remain unchanged.

Let me know in case you want me to investigate further.

**Comment by ArtificialOwl** [comment] 2021-08-01 12:42
> NC log contains this line after running occ circles:check:
> `{"reqId":"f4GhzFHjElgikf6VQDEv","level":3,"time":"2021-07-30T14:42:33+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Directive 'allow_url_include' is deprecated at Unknown#0","userAgent":"--","version":"22.1.0.0","id":"61040fd9a5636"} `

This comes from the fact that `allow_url_include` is set to _On_ in `/etc/php/[...]/cli/php.ini`:

>      allow_url_include = Off

Now, are you sure that your httpd returns the right instance of Nextcloud when trying to reach your Nextcloud from the server using https://.../nc22/index.php ?

Anyway, we will have a release of NC22.1.0 on Tuesday, I will do some more test on my side and merge this PR. This will make the upgrade step a lot easier.

**Comment by czenk** [comment] 2021-08-01 17:30
Thank you - and no worries. I will try to make sure I get a chance to test against the upcoming release on Wednesday and to report back.

In case it is of any help with regards to your tests:

> Now, are you sure that your httpd returns the right instance of Nextcloud when trying to reach your Nextcloud from the server using https://.../nc22/index.php ?

Everything is possible ;-) - so I tried to verify via two quick tests as a sanity check against https://.../22/ as well as https://.../22/index.php and https://.../22/index.html (via web browser) a moment ago: 
1. Renaming the top-level folder of every other nextcloud instance (all release 21-) on the webspace (thus breaking them). 
    Result: NC22 staging instance is working
2. Removing index.php as well as the redirect from index.html of the NC22 staging instance. 
    Result: Test instance is broken

Do not hesitate to let me know should you want me to test anything else in advance of the release.

**Comment by Mannshoch** [comment] 2021-08-09 17:52
I changed to the Beta channel and updated to **22.1.0.0**
Same problem. Circles do not work.
From the above feedback I got the hint to check on OCC  `occ circles:check`
I get 

```
### Checking loopback address.
. The loopback setting is mandatory and can be checked locally.
. The address you need to define here must be a reachable url of your Nextcloud from the hosting server itself.
. By default, the App will use the entry 'overwrite.cli.url' from 'config/config.php'.

* testing current address: https://host.domain.tld
- GET request on https://host.domain.tld/index.php/csrftoken: 200
- POST request on https://host.domain.tld/index.php/apps/circles/async/test-dummy-token/: fail

- You do not have a valid loopback address setup right now.

```
Any Idea what I should enter into the Loopback address?

**Comment by ArtificialOwl** [comment] 2021-08-09 19:42
Can you try to add a trailing slash to the address defined as `overwrite.cli.url` in `config/config.php`

**Comment by Mannshoch** [comment] 2021-08-10 11:25
I tried both: 
```
### Checking loopback address.
. The loopback setting is mandatory and can be checked locally.
. The address you need to define here must be a reachable url of your Nextcloud from the hosting server itself.
. By default, the App will use the entry 'overwrite.cli.url' from 'config/config.php'.

* testing current address: https://host.domain.tld
- GET request on https://host.domain.tld/index.php/csrftoken: 200
- POST request on https://host.domain.tld/index.php/apps/circles/async/test-dummy-token/: fail

- You do not have a valid loopback address setup right now.

Please write down a new loopback address to test: https://host.domain.tld/
* testing address: https://host.domain.tld - GET request on https://host.domain.tld/index.php/csrftoken: 200
- POST request on https://host.domain.tld/index.php/apps/circles/async/test-dummy-token/: fail

```
and I changed in config:
`'overwrite.cli.url' => 'host.domain.tld',`
to
`'overwrite.cli.url' => 'host.domain.tld/',`

same result.

**Comment by Mannshoch** [comment] 2021-08-19 07:14
I Installed Isssue Template and attache here the resulting data. Any other Data yu need?

## Server configuration detail
**Operating system:** Linux 3.10.0-1160.25.1.el7.x86_64 # 1 SMP Wed Apr 28 21:49:45 UTC 2021 x86_64
**Webserver:** Apache (cgi-fcgi)
**Database:** sqlite3 3.7.17

**PHP version:** 
8.0.9
Modules loaded: Core, date, libxml, openssl, pcre, zlib, bz2, calendar, ctype, hash, filter, ftp, gettext, gmp, SPL, iconv, json, pcntl, readline, Reflection, session, standard, SimpleXML, sockets, mbstring, tokenizer, xml, cgi-fcgi, mysqlnd, bcmath, curl, dba, dom, fileinfo, gd, imagick, imap, intl, ldap, exif, mysqli, odbc, PDO, pdo_mysql, PDO_ODBC, pdo_sqlite, Phar, posix, pspell, redis, soap, sodium, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 22.1.0 - 22.1.0.1

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.7.0
 - activity: 2.15.0
 - analytics: 3.6.0
 - bookmarks: 4.4.0
 - bruteforcesettings: 2.2.0
 - calendar: 2.3.2
 - circles: 22.1.0
 - cloud_federation_api: 1.4.0
 - collectives: 0.12.22
 - comments: 1.11.0
 - contacts: 4.0.1
 - contactsinteraction: 1.2.0
 - dashboard: 7.1.0
 - dav: 1.18.0
 - deck: 1.5.0
 - event_update_notification: 1.3.0
 - external: 3.9.0
 - federatedfilesharing: 1.11.0
 - federation: 1.11.0
 - files: 1.16.0
 - files_accesscontrol: 1.12.0
 - files_automatedtagging: 1.12.0
 - files_external: 1.12.1
 - files_pdfviewer: 2.3.0
 - files_rightclick: 1.1.0
 - files_sharing: 1.13.2
 - files_trashbin: 1.11.0
 - files_versions: 1.14.0
 - files_videoplayer: 1.11.0
 - firstrunwizard: 2.11.0
 - flow_notifications: 1.2.0
 - issuetemplate: 0.7.0
 - logreader: 2.7.0
 - lookup_server_connector: 1.9.0
 - mail: 1.10.3
 - maps: 0.1.9
 - nextcloud_announcements: 1.11.0
 - notes: 4.1.1
 - notifications: 2.10.1
 - oauth2: 1.9.0
 - onlyoffice: 7.1.2
 - password_policy: 1.12.0
 - photos: 1.4.0
 - polls: 3.0.0
 - privacy: 1.6.0
 - provisioning_api: 1.11.0
 - recommendations: 1.1.0
 - serverinfo: 1.12.0
 - settings: 1.3.0
 - sharebymail: 1.11.0
 - spreed: 12.0.1
 - support: 1.5.0
 - survey_client: 1.10.0
 - systemtags: 1.11.0
 - tasks: 0.14.1
 - text: 3.3.0
 - theming: 1.12.0
 - twofactor_backupcodes: 1.10.1
 - updatenotification: 1.11.0
 - user_status: 1.1.1
 - viewer: 1.6.0
 - weather_status: 1.1.0
 - workflow_media_converter: 1.2.10
 - workflow_ocr: 1.22.1
 - workflow_pdf_converter: 1.7.0
 - workflowengine: 2.3.0
Disabled:
 - admin_audit
 - encryption
 - richdocuments
 - richdocumentscode
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "host.domain.tld"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "sqlite3",
    "version": "22.1.0.1",
    "overwrite.cli.url": "host.domain.tld/",
    "htaccess.RewriteBase": "/",
    "installed": true,
    "default_language": "de",
    "mail_smtpmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtpauthtype": "LOGIN",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpsecure": "ssl",
    "logtimezone": "Europe/Berlin",
    "default_phone_region": "CH",
    "maintenance": false,
    "updater.release.channel": "stable",
    "theme": "",
    "syslog_tag": "TEST",
    "loglevel": 2,
    "app_install_overwrite": [
        "issuetemplate"
    ]
}
```
</details>

**Comment by czenk** [comment] 2021-08-20 12:38
Sorry for the late update from me - my instance(s) did not display an update offer until yesterday:

Update 22.1 stable applied via web updater (no errors).  
Here is a list of symptoms as reported in my first post, together with status update:

Symptoms:
- [Resolved] -> No icon for 'Circles'
- [Resolved] -> Error message in log as reported by Mannshoch
- [Not Resolved] -> Icon to access 'Circles' UI missing from users top level app task bar, no access to a dedicated end-user ui for management of Circles (compared to NC 21 installed in same environment - see below)
- [Resolved] -> After creation of a Circle from 'Contacts App' and sharing a file with the Circle, Circle participants cannot gain visibility of the items shared with/contained in the Circle
- [Resolved] -> Deleting a Circle from the 'Contacts App': Circle removed from user view, but after leaving/reentering the Contacts App the previously deleted Circle is visible again. Same for attempts to remove members from Circle
 
[Resolved] occ circles:check executed in a shell (no nc user session) yields:

> GET request on https://host.domain.com/index.php/csrftoken: 403



[Not Resolved] occ circles:check executed in  a shell (no nc user session) yields:

> POST request on https://host.domain.tld/22/index.php/apps/circles/async/test-dummy-token/: fail

(tried with and without trailing slash in config.php against 'overwrite.cli.url')

[New]
Users now see a representation of a file shared with them via a circle. They can only access file contents though for as long as the file creator is viewing/editing the file. Once the creator closes the file, other users cannot access the file contents anymore.
Note: This setup is using per-user key file encryption.
The following two error message are displayed in the logs when a member of a circle tries to read a file shared with her/him whilst the file creator does not have the file open (let me know in case you want the logs in raw format):
> [text] Error: Cannot decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.
PUT /22/index.php/apps/text/session/create
from [removed] by [removed] at 2021-08-20T12:11:43+00:00
[no app in context] Error: Cannot decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.
PUT /22/index.php/apps/text/session/create
from [removed] by [removed] at 2021-08-20T12:11:43+00:00

Do not hesitate to let me know in case you want me to log a separate ticket for the encryption issue.

Thank you and do let me know in case I can be of further assistance.

**Comment by lorenzo-w** [comment] 2021-08-30 10:41
@czenk Can you tell me the full version of your installation please? I am running Nextcloud 22.1.1 and still experiencing the issue that files shared with circles are not visible.

**Comment by ArtificialOwl** [comment] 2021-08-30 12:37
@lorenzo-w can you paste the result of `./occ circles:check` on your NC22.1.1 ?

**Comment by czenk** [comment] 2021-08-30 12:46
> 
> 
> @czenk Can you tell me the full version of your installation please? I am running Nextcloud 22.1.1 and still experiencing the issue that files shared with circles are not visible.

My last report was against version 22.1.0.1. I just checked again and was offered 22.1.1.2:
Applied and ran through the same procedure as for my last report - yielding the same results.
Additional info:
PHP 7.4.19
mysql(mariadb) 10.5.11
Linux 5.4.0-81-generic x86_64 (shared web host on Apache)

**Comment by lorenzo-w** [comment] 2021-08-30 12:53
Almost the same as mine:
Nextcloud 22.1.1.2
PHP 7.4.22
MariaDB 10.5.11
System is some linux flavor, can't say more as I'm also operating on a shared Apache instance and have no ssh access

But the issue persists...

**Comment by ArtificialOwl** [comment] 2021-08-30 12:53
@czenk  have you tried to follow the instruction and provide an other address to test during the `./occ circles:check` ?

**Comment by czenk** [comment] 2021-08-30 13:12
> 
> 
> @czenk have you tried to follow the instruction and provide an other address to test during the `./occ circles:check` ?

@ArtificialOwl, not sure if I did this correctly - but here is what I just verified again:
1. Attempted to manually provide 
- https://host.domain.tld/22
- https://host.domain.tld/22/

2. Changed config.php from:
'overwrite.cli.url' => 'host.domain.tld/22'
to
'overwrite.cli.url' => 'host.domain.tld/22/'

Result remains unchanged:

> * testing current address: https://host.domain.tld/22(/)
> - GET request on https://host.domain.tld/22/index.php/csrftoken: 200
> - POST request on https://host.domain.tld/22/index.php/apps/circles/async/test-dummy-token/: fail
> 
> - You do not have a valid loopback address setup right now.

Root of nextcloud install at https://host.domain.tld/22

Let me know in case you want me to test anything else.

**Comment by mic05** [comment] 2021-09-05 15:25
Just wanted to say that I have the same issue. Just installed Nextcloud 22.1.1 on a freshly installed Ubuntu 20.04 with nginx and PHP 8.0. Circles-App is not visible in the navigation bar and when accessing https://nextcloud.domain.tld/apps/circles only `[]` is displayed.
I've digged into this a bit deeper and have seen that nginx logs error 499 in access log to the POST request of `occ circles:check`. In the error log of nginx at info level the following is logged:
`2021/09/05 17:17:29 [info] 1378#1378: *23 client 127.0.0.1 closed keepalive connection
2021/09/05 17:17:34 [info] 1378#1378: *25 epoll_wait() reported that client prematurely closed connection, so upstream connection is closed too while sending request to upstream, client: 127.0.0.1, server: nextcloud.domain.tld, request: "POST /index.php/apps/circles/async/test-dummy-token/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php-fpm.sock:", host: "nextcloud.domain.tld"`

So to me it seems that the circles app is closing the connection but I don't know why.

**Comment by aaaaaaaaargh** [comment] 2021-09-07 15:08
> Just wanted to say that I have the same issue. Just installed Nextcloud 22.1.1 on a freshly installed Ubuntu 20.04 with nginx and PHP 8.0. Circles-App is not visible in the navigation bar and when accessing https://nextcloud.domain.tld/apps/circles only `[]` is displayed.
> I've digged into this a bit deeper and have seen that nginx logs error 499 in access log to the POST request of `occ circles:check`. In the error log of nginx at info level the following is logged:
> `2021/09/05 17:17:29 [info] 1378#1378: *23 client 127.0.0.1 closed keepalive connection 2021/09/05 17:17:34 [info] 1378#1378: *25 epoll_wait() reported that client prematurely closed connection, so upstream connection is closed too while sending request to upstream, client: 127.0.0.1, server: nextcloud.domain.tld, request: "POST /index.php/apps/circles/async/test-dummy-token/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php-fpm.sock:", host: "nextcloud.domain.tld"`
> 
> So to me it seems that the circles app is closing the connection but I don't know why. Maybe this is because of a timeout in the occ circles:check command but this would mean that there is another error. Maybe if the occ command wouldn't terminate the connection there would be a 504 error, but this is just speculation.
> 
> Edit: I think this test isn't very good for this issue. As mentiond [here](https://github.com/nextcloud/circles/issues/725#issuecomment-904742059) #725 there is an issue with the test but even if you change this and the test succeeds, the circles app doesn't work.

Exact same problem here. This is a nightmare for a business use case (which unfortunately is for me). Anything I could do to help solving the issue? circles:check worked fine for me once I set the correct loopback address. Mine was using http instead of https but this is something that I kind of expected because nextcloud is running behind a reverse proxy here.

**Comment by ArtificialOwl** [comment] 2021-09-07 15:58
Can you send me the full result of your `./occ circles:check` ?

Please note that the `Circles App` is only a back-end app now and have no front-end provided anymore. You will need the `Contacts App` to manage your Circles. 

It is totally normal that `https://nextcloud.domain.tld/apps/circles` returns an empty array. The only way to have something from this URL is to enable to communication with remote instances using `./occ circles:check` (and send "Accept: application/json" as header of the GET request)

**Comment by aaaaaaaaargh** [comment] 2021-09-07 16:29
> Can you send me the full result of your ./occ circles:check ?
I'm so sorry, I was desperate to do something so I rolled back to NextCloud 21 to solve the issue. That means I cannot give you any more information on that but as far as I know there was nothing wrong, the check just passed, also the async part which some users seem to have problems with passed as expected (after 5 secs of course).

> You will need the Contacts App to manage your Circles.
Now I feel dumb. I may have forgotten about that. To be fair, I wasn't aware about that and there may be a chance that the Contacts app was disabled during the update. I cannot confirm that, but I can't remember to have seen anything like this. On the other hand, we're not using NextCloud for contact management, so this just might have escaped my attention.

I will try to repeat the progress of upgrading to NC 22 in a sandbox again. We need to upgrade anyway, so when I am doing that, I would be happy to share all the results here!

**Comment by mic05** [comment] 2021-09-08 09:24
Sorry for that. After installing the contacts App everything is working fine. I wasn't aware of that dependence. Thanks.

**Comment by douardda** [comment] 2021-09-12 19:41
Hi, can't make circles:check pass either (same failure on the POST request). 
fresh install of a NC22.1.1 (debian 11, postgresql 13, php7.4).

If I try a dummy post on that URL by hand, I do get an 200 response but it takes a while (5 or 6s):

When I execute the circles:check command, I can see liburl error (generated by occ) in the logs (level 0) about a timeout being reached (`cURL error 28: Operation timed out after 5001 milliseconds with 0 bytes received`)

Looks like a DNS issue or something.

**Comment by douardda** [comment] 2021-09-12 20:07
After hacking the timeout value in the dummy-token handler, the circles:check pass ok. 

I cannot see an icon for the Circle app, but I can create circles from the contact app. It seems this has been changes (more or less) recently, but I've seen no mention/documentation about it. Did I miss something?

(I mean the screenshot still shows a icon and dedicated app for example)

**Comment by SitalexUniversel** [comment] 2021-10-05 08:28
circles не работают
circles not work
Deleting circles fail


occ circles:check fails

Два шага.

Шаг первый:
мой вариант:
'overwrite.cli.url' => 'https://your-server.ru/nextcloud/',

Шаг второй:
проверьте как отзывается ваш сервер
ping your-server.ru 

ответ должен быть:
your-server.ru   (ваш ip)   , если это не так, тогда изменить /etc/hosts
127.0.0.1    localhost
xxx.xxx.xxx.xxx     your-server.ru

xxx.xxx.xxx.xxx --- это ваш ip.

**Comment by ramrajone** [comment] 2021-10-06 19:05
I have a similar issue after the upgrade to Version 22.2.0

Changing time from 5s to 4s did not fix the issue: Reduce the sleep time in test-dummy-token handler #811

The only way to get it working is by disabling the circle app

**Comment by hadirsa** [comment] 2021-12-05 14:57
Any update on this issue?

**Comment by Sysadminfromhell** [comment] 2021-12-06 19:20
Is there any update? we using Circles to organize our e-Sports club and teams with it. But Circles + Collectives doesnt work.

Next Cloud v22.2.3

**Comment by ArtificialOwl** [comment] 2021-12-06 20:27
It would be nice to open new tickets regarding your issue, with the result of your `./occ circles:check`

**Comment by frocelu** [comment] 2021-12-16 08:34
I got this bug, too.
But I pass `./occ circles:check` and still can not see the Icon of circles
Access the URL https://domain/app/circles just output an empty array []

Nextcloud version: 22.2.3
'overwrite.cli.url' already changed to correct url
php ver: 8.0.13

**Comment by ramrajone** [comment] 2022-01-03 21:08
This issue is still there on version: Nextcloud Hub II (23.0.0)

**Comment by ArtificialOwl** [comment] 2022-01-04 00:11
> It would be nice to open new tickets regarding your issue, with the result of your `./occ circles:check`

**Closed** 2022-04-19 12:55 UTC

**Comment by punkyard** [comment] 2022-12-02 22:41
hi, i have the same issue with 24.0.7
i've tried what's indicated above, but no luck.

Changed overwrite.cli.url' => 'localhost', to my url, with and without /
Tried different addresses when it's prompted:
```
You do not have a valid loopback address setup right now.
Please write down a new loopback address to test: 
```
my allow_url_include is 'Off'

Would one have a lead for me please?
Thanks a if you can share your experience.
have a nice weekend
