### ISSUE TITLE
Circles tool entirely missing on the top tool bar

### ISSUE THREAD

**Issue by ASmith-** [nextcloud/circles#837] opened 2021-10-31 20:21 UTC
Circles tool entirely missing on the top tool bar

Well over a dozen Circles with subscribers are missing, sharing doesn't appear to be active on multiple Circles, while set on some. I've tried resetting the sharing ability but that is acting non-functionable. 

Tried to disable and enable Circles, that didn't bring back that tool icon either. 

My administrative ability to work on my tool order is missing. I've tried disabling some tools to see if those features return, they didn't.

Nextcloud 22.2.0
Snap installed, Linux Mint 20.1 Ulyssa

**Comment by svenseeberg** [comment] 2021-11-30 16:42
I think this is a duplicate of #830 . The Circles management was moved into the Contacts tab.

**Closed** 2022-03-04 09:54 UTC
