### ISSUE TITLE
self-signed certificate error

### ISSUE THREAD

**Issue by arefaydi** [nextcloud/circles#212] opened 2018-07-09 10:19 UTC
While I share a file with a circle, this error occurs :
**_cURL error 60: SSL certificate problem: self signed certificate_**
File shared successfully but it didn't shown on the share tab until reload page. SSL enabled with self signed certificate.

**Comment by DanieleCir** [comment] 2018-10-02 14:42
I can confirm the same issue, when I try to share with a Circle_group.
Version in use: NC-14 all updated from "stable channel".
I'm using a regualar/valid certificate got from GlobalSign (not self signed); it is a wildcard certificate, used for:  *.domain.ext
The server I created is called like  nc.**domain.ext**

I just added:
[curl]
curl.cainfo = /etc/curl_ca/cacert.pem
to my php.ini after I downloaded the most updated cacert.pem from this link: https://curl.haxx.se/ca/cacert.pem

But the problem is still there.

Any suggestion?

Thank you.
Daniele

**Comment by daita** [comment] 2018-10-30 08:30
please try:

`./occ config:app:set circles --value 1 allow_non_ssl_links`

if it is not enough:

`./occ config:app:set circles --value 1 local_is_non_ssl`

**Comment by wiswedel** [comment] 2019-08-23 09:10
resolved by #322

**Closed by wiswedel** 2019-08-23 09:10 UTC
