### ISSUE TITLE
Only run migration to 22 once

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/circles#796] opened 2021-08-24 11:25 UTC
It seems that the migration step to migrate circles to 22 can be executed multiple times. I just noticed that when running `occ maintenance:repair` the step gets executed every time the command is ran, so most likely also for every upgrade:

```
 - Upgrading Circles App
     - (Circles) Migrating to 22
 2252/2786 [======================>-----]  80%
```

This is rather slow, especially on larger setups and shouldn't be needed anymore once migrated once from my POV.

**Comment by ArtificialOwl** [comment] 2021-08-30 11:48
Can you check the value of migration_* when running `./occ config:list circles` ?

**Comment by svenseeberg** [comment] 2021-11-30 16:40
I'm not sure yet if this is really related, but it seems the check is not working correctly anyways, see #858. I had to manually run the migration command with the force flag to finish the migration.

**Comment by ArtificialOwl** [comment] 2021-12-08 12:36
I will close this ticket. I just ran multiple migration run from 21 -> 22.1.0 -> 22.2.3 -> 23.0.0. cannot reproduce this issue.

**Closed by ArtificialOwl** 2021-12-08 12:36 UTC
