### ISSUE TITLE
There is a flaw in the mechanism for getting in and accepting invitations in a closed circle.

### ISSUE THREAD

**Issue by Retr02332** [nextcloud/circles#635] opened 2021-06-22 03:00 UTC
Hello nextcloud team

The version of the software and the app I use are as follows:

Nextcloud 21.0.2
Circles 0.21.2

When a person wants to join a closed circle, they must send a request and wait for the owner to accept it.

The bug here is that when the owner accepts the user, the user never actually joins.

On the other hand, when an owner invites a user to join, the user must accept the invitation in order to join.

The error here is that the user cannot accept the invitation, there is no option to do so, the only option available is to request to join (when it is not necessary because the user has already been invited).

Even so when the owner receives this request and "accepts" the user, in reality as I said in the first problem, the user never enters the circle.

Regards,
Retr0

**Comment by Retr02332** [comment] 2021-07-04 02:40
any update?

**Comment by nate1908** [comment] 2022-04-20 14:20
I am very surprised that this has not been looked at as this means Circles is total unusable. Status is stuck on "Requesting"

**Comment by joshtrichards** [comment] 2024-06-13 20:46
I cannot reproduce either of these scenarios today. Closing this out as there have not been further similar reports. If someone is experiencing this today, please create a dedicated issue with the details of your environment.

**Closed by joshtrichards** 2024-06-13 20:46 UTC
